spring.application.name=crude-students
spring.datasource.url=jdbc:mysql://localhost:3306/student_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=student_app
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
server.port=8081
spring.jpa.show-sql=true
